"""crear modelos voluntarios

Revision ID: 0f59798cd66b
Revises: 
Create Date: 2026-02-14 11:09:39.754754

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f59798cd66b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('permisos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('voluntarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keycloak_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fecha_alta', sa.Date(), nullable=False),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('foto_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'BAJA', 'SUSPENDIDO', name='estado_voluntario', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_voluntarios_keycloak_id'), 'voluntarios', ['keycloak_id'], unique=True)
    op.create_table('disponibilidades',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voluntario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['voluntario_id'], ['voluntarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voluntario_id', 'fecha', name='uq_disponibilidad_voluntario_fecha')
    )
    op.create_index(op.f('ix_disponibilidades_voluntario_id'), 'disponibilidades', ['voluntario_id'], unique=False)
    op.create_table('formaciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voluntario_id', sa.Uuid(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('fecha_obtencion', sa.Date(), nullable=False),
    sa.Column('fecha_caducidad', sa.Date(), nullable=True),
    sa.Column('certificado_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['voluntario_id'], ['voluntarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formaciones_voluntario_id'), 'formaciones', ['voluntario_id'], unique=False)
    op.create_table('voluntario_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('voluntario_id', sa.Uuid(), nullable=False),
    sa.Column('rol_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_desde', sa.Date(), nullable=False),
    sa.Column('fecha_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['voluntario_id'], ['voluntarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voluntario_roles_rol_id'), 'voluntario_roles', ['rol_id'], unique=False)
    op.create_index(op.f('ix_voluntario_roles_voluntario_id'), 'voluntario_roles', ['voluntario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voluntario_roles_voluntario_id'), table_name='voluntario_roles')
    op.drop_index(op.f('ix_voluntario_roles_rol_id'), table_name='voluntario_roles')
    op.drop_table('voluntario_roles')
    op.drop_index(op.f('ix_formaciones_voluntario_id'), table_name='formaciones')
    op.drop_table('formaciones')
    op.drop_index(op.f('ix_disponibilidades_voluntario_id'), table_name='disponibilidades')
    op.drop_table('disponibilidades')
    op.drop_index(op.f('ix_voluntarios_keycloak_id'), table_name='voluntarios')
    op.drop_table('voluntarios')
    op.drop_table('roles')
    # ### end Alembic commands ###
